spring:
  application:
    name: arquetipofirestore
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        location: file:${GCP_APP_CREDENTIALS}
      datastore:
        namespace: ${GCP_DATASTORE_NAMESPACE}
service:
  dateFormat: yyyy-MM-dd hh:mm:ss
  controller:
    path: /api/v1/persona
  message:
    error:
      default: Error de microservicio, porfavor intentar más tarde
      validation: Error en validación de datos
      file: No se puede leer el archivo de catalogo de errores
  errorCatalog:
    path: src/main/resources/errorCatalog.json
server:
  port: 8087